language: node_js
node_js:
- 14.18.2
branchs:
  only:
  - master
cache:
  apt: true
  directories:
  - node_modules
before_install:
- curl -f https://get.pnpm.io/v5.js | node - add --global pnpm@5
- pnpm config set store-dir ~/.pnpm-store
- openssl aes-256-cbc -K $encrypted_a2df9b418bbc_key -iv $encrypted_a2df9b418bbc_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 39.104.15.110\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
install:
- git pull --rebase
- yarn install
script:
- yarn build
after_success:
- chmod 600 ~/.ssh/id_rsa
- rm -rf root@39.104.15.110:/var/www/mobile/*
- scp -o stricthostkeychecking=no -r ./dist/* root@39.104.15.110:/var/www/mobile
    
